const template = [
'!0',
'<?xml version="1.0" encoding="utf-8"?>',
'<layer-list xmlns:android="http://schemas.android.com/apk/res/android">',
'!1',
'	<item>',
'		<shape android:shape="rectangle">',
'			<solid android:color="@color/{&color}" />',
'		</shape>',
'	</item>',
'!1',
'!2',
'	<item android:top="{@top}" android:left="{@left}" android:drawable="@drawable/{image}" width="{@width}" height="{@height}" />',
'!2',
'!3',
'	<item android:top="{@top}" android:left="{@left}">',
'		<bitmap android:src="@drawable/{image}" android:gravity="{@gravity}" android:tileMode="{@tileMode}" android:tileModeX="{@tileModeX}" android:tileModeY="{@tileModeY}" />',
'	</item>',
'!3',
'!4',
'	<item android:top="{@top}" android:right="{@right}" android:bottom="{@bottom}" android:left="{@left}">',
'		<shape android:shape="rectangle">',
        '!5',
'			<stroke android:width="{&width}" {borderStyle} />',
        '!5',
        '!6',
'			<corners android:radius="{&radius}" />',
        '!6',
        '!7',
'			<corners android:topLeftRadius="{@topLeftRadius}" android:topRightRadius="{@topRightRadius}" android:bottomRightRadius="{@bottomRightRadius}" android:bottomLeftRadius="{@bottomLeftRadius}" />',
        '!7',
'		</shape>',
'	</item>',
'!4',
'</layer-list>',
'!0'
];

export default template.join('\n');