const template = [
'<?xml version="1.0" encoding="utf-8"?>',
'<vector xmlns:android="http://schemas.android.com/apk/res/android" {~namespace} android:width="{&width}" android:height="{&height}" android:viewportWidth="{&viewportWidth}" android:viewportHeight="{&viewportHeight}" android:alpha="{~alpha}">',
'!1',
'	<group android:name="{~name}" android:rotation="{~rotation}" android:pivotX="{~pivotX}" android:pivotY="{~pivotY}" android:scaleX="{~scaleX}" android:scaleY="{~scaleY}" android:translateX="{~translateX}" android:translateY="{~translateY}">',
    '!2',
'		<clip-path android:name="{~name}" android:pathData="{&d}" />',
    '!2',
    '!3',
'		<path',
'			android:name="{~name}" android:fillType="{~fillRule}" android:fillColor="{~fill}" android:fillAlpha="{~fillOpacity}" android:strokeColor="{~stroke}" android:strokeWidth="{~strokeWidth}" android:strokeAlpha="{~strokeOpacity}" android:strokeLineCap="{~strokeLineCap}" android:strokeLineJoin="{~strokeLineJoin}" android:strokeMiterLimit="{~strokeMiterLimit}"',
'			android:pathData="{&d}">',
        '!fill',
'			<aapt:attr name="android:fillColor">',
            '!gradients',
'				<gradient android:type="{&type}" android:startColor="@color/{~startColor}" android:endColor="@color/{~endColor}" android:centerColor="@color/{~centerColor}" android:startX="{~startX}" android:startY="{~startY}" android:endX="{~endX}" android:endY="{~endY}" android:centerX="{~centerX}" android:centerY="{~centerY}" android:gradientRadius="{~gradientRadius}">',
                '!colorStop',
'					<item android:offset="{&offset}" android:color="{&color}" />',
                '!colorStop',
'				</gradient>',
            '!gradients',
'			</aapt:attr>',
        '!fill',
'		</path>',
    '!3',
'	</group>',
'!1',
'</vector>',
];

export default template.join('\n');